<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CookieTableRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CookieTableRepository extends EntityRepository
{
}
