<?php

/*
 * This file is part of the Inspection Copy.
 * Copyright (C) 2019 Elsevier.
 * Created by mobelite.
 *
 * Date: 4/11/18
 * Time: 17:38
 * @author: Mobelite <www.mobelite.fr>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

class FaqRepository extends EntityRepository
{

    /**
     * FaqRepository
     *
     * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
     * repository methods below.
     */
}
