<?php

namespace UserBundle\Repository;

use UserBundle\Entity\RequestRegister;

/**
 * RequestRegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRegisterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $token
     * @param $maxValidTime
     * @return null|RequestRegister
     */
    public function findValidToken($token, $maxValidTime): ?RequestRegister
    {
        $result = $this->createQueryBuilder('rr')
            ->where('rr.token = :token')
            ->andWhere('rr.requestedAt > :validDate')
            ->setParameters(['token' => $token, 'validDate' => $maxValidTime])
            ->getQuery()->getResult();
        return count($result) > 0 ? $result[0] : null;
    }

    /**
     * Delete registration by email
     * @param string $email
     */
    public function deleteOldRegistrationByEmail(string $email)
    {
        $this->createQueryBuilder('e')
            ->delete()
            ->where('e.email = :email')
            ->setParameter('email', $email)
            ->getQuery()->execute();
    }
}
