name: Clear Cache & Restart
on:
  workflow_dispatch:
    inputs:
      release_env:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  Clear-Cache:
    runs-on: 
      - self-hosted
      - ephemeral
      - "${{ github.event.inputs.release_env }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
        unzip -q /tmp/awscliv2.zip -d /tmp
        rm /tmp/awscliv2.zip
        sudo /tmp/aws/install --update
        rm -rf /tmp/aws/
    - name: "Clear Cache: ${{ github.event.inputs.release_env }}"
      run: |
        bash ${GITHUB_WORKSPACE}/.github/scripts/deploy.sh \
        ${{ github.event.inputs.release_env }} \
        IC-ClearCache \
        "IC Clear Cache: ${{ github.event.inputs.release_env }}"
