name: Deploy-InspectionCopy

on:
  push:
    branches:
      - main 
      - staging
env:
  build_path: /var/www/inspectioncopy.staging.mobelite.fr
jobs:
  deploy-inspectioncopy:
    runs-on: icopy-staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarScanner
        run: echo "export PATH=$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV

      - name: Set up SonarScanner
        run: which sonar-scanner
        
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          
      - name: Rsync InspectionCopy
        run: |
         rsync -rauv . --exclude log --exclude vendor --exclude config.php $build_path
         
      - name: Update composer and database
        run: |
         cd $build_path && composer update && php vendor/bin/doctrine orm:schema-tool:update --force
         
      #- name: Clear cache
       # run: |
        # cd $build_path && ./postbuild.sh

         
