name: Staging Pipeline with SonarCloud and PHP Code Sniffer

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main 
      - develop

jobs:
  buildArtifact:
    runs-on: ubuntu-latest
    name: Build Artifact and Analyze Code
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHP dependencies
        run: composer install

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 7.4
          path: src/
          standard: ruleset.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
