name: staging pipeline
on:
  pull_request:
    branches:
      - main
      - staging
      
  push:
    branches:
      - main 
      - staging
jobs:
  buildArtifact:
    runs-on: ubuntu-latest
    name: buildArtifact
    steps:
      - name: github-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      #"##############################"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: hanine16/php-proj:latest
          cache-from: type=registry,ref=hanine16/php-proj:latest
          cache-to: type=inline

      - name: Deploy Image
        run: echo ${{ steps.docker_build.outputs.digest }}
      #"##############################"
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/hanine16/php-proj:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Notification Slack 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: new code
          SLACK_USERNAME: Github_Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "new version of application ${GITHUB_SHA}"
