name: staging pipeline
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  buildArtifact:
    runs-on: ubuntu-latest
    name: buildArtifact
    steps:
      - name: github-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/docker-login@v1
        with:
          login-server: stagepfe.azurecr.io
          username: stagePFE
          password: ${{ secrets.ACR_PASSWORD }}
      - name: build artifact
        run: |
          docker build -t stagepfe.azurecr.io/inspection-copy:$(echo ${GITHUB_SHA} | cut -c1-7) .
#          docker push stagepfe.azurecr.io/inspection-copy:$(echo ${GITHUB_SHA} | cut -c1-7)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "stagepfe.azurecr.io/inspection-copy:${{ github.sha | slice(0, 7) }}"
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
